### ISSUE TITLE
Green Talk Circle Shape Mismatch.

### ISSUE THREAD

**Issue by KittyHanahara** [discord-extensions/essence#11]
In DM calls, and in the bottom left, 
the green talk circle is still perfectly round, and the profile image doesn't line up when talking in a VC.
![ScuffedTalkCircle](https://user-images.githubusercontent.com/53832899/176755930-d249c70d-2d0c-4dd6-94d6-332bed5744a1.png)

I'm not sure if this is just me or not, I have all other plugins disabled, and themes either disabled or completely removed.

Client Info:
Stable 134335 (a128825)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.22000)

Theme Versions: 1.1.0

**Comment by rat182** [comment]
it's not just you, it's a problem with the theme itself.

**Comment by LuckFire** [comment]
yea i'll have this fixed the next push i make

**Comment by LuckFire** [comment]
should be fixed in v1.1.1
