### ISSUE TITLE
No proper styling at MenuGroup

### ISSUE THREAD

**Issue by abUwUser** [discord-extensions/essence#13]
The component known as MenuGroup is not properly styled as it should be. The result above is reached with the usage of a plugin
![image](https://user-images.githubusercontent.com/27961224/177471587-13da99bd-1bff-4827-9452-0d2c19b5cb2d.png)

You can find it at discord in a thread by going to the three-dot menu > Archive
![image](https://user-images.githubusercontent.com/27961224/177472105-23c634c3-32bd-4c8d-8b87-91e2e9277da3.png)

**Comment by LuckFire** [comment]
fixed in v1.2.0
