### ISSUE TITLE
Status circle big when someone is typing or typed

### ISSUE THREAD

**Issue by AdriGeeK03** [discord-extensions/essence#4]
![image](https://user-images.githubusercontent.com/50402620/176287961-3088a933-25e3-484e-9235-af69a764254f.png)

Hey I just downloaded this theme, I love it but I found that issue and its kind of a big deal (in my opinion). 
Hope you'll manage to fix it.
Thx again :)

**Comment by LuckFire** [comment]
i wasn't too sure what was causing it at first but after checking you seem to be right, ill push something in a bit to resolve this

**Comment by LuckFire** [comment]
this should be fixed with v1.0.2
the typing indicators are completely gone but ill hopefully figure out something in the future to make it look nice
