### ISSUE TITLE
Feature Request: Horizontal Server List

### ISSUE THREAD

**Issue by KeryWT** [discord-extensions/essence#8]
Hi,
First of all, wonderful theme!
Anyway, I tried to mix it with the Horizontal Server List theme, but it's got a few bugs here and there.
Would you please take into consideration adding it as an option in your theme?
Thanks for your time.

**Comment by LuckFire** [comment]
ill look into this later :+1:

**Comment by LuckFire** [comment]
v1.1.0 adds this, you have to add this (preferably below addons but it doesn't matter much) into the themes file:
```css
@import url('https://discord-extensions.github.io/essence/src/vendors/horizontal-server-list.css');
```
this was the only way i could really add support for it
