### ISSUE TITLE
Light Nord theme

### ISSUE THREAD

**Issue by maicol07** [discord-extensions/essence#9]
Hi,
can you add a light version of the nord theme?
Thanks

**Comment by LuckFire** [comment]
nord doesn't have an official light mode palette from what i know

**Comment by maicol07** [comment]
There's the Snow storm palette: https://www.nordtheme.com/docs/colors-and-palettes

**Comment by LuckFire** [comment]
> Snow Storm is made up of three bright colors that are commonly used for text colors or base UI elements in bright ambiance designs.

It's more of meant to be used in very specific places from what I could tell, but I could be wrong
